import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "600", "700", "800"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "DeshIT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${poppins.variable} scroll-smooth`}
    >
      <body className="antialiased bg-white">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
